name: GitHub Actions Demo
on: [push]
jobs:
  Get-All-List:
    runs-on: ubuntu-latest
    env:
      GEOIP: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
      GEOSITE: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
      GFWLIST: https://raw.github.com/gfwlist/gfwlist/master/gfwlist.txt
      CHNLIST: https://raw.github.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
      APNICIP: http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest
      OISD: https://dbl.oisd.nl/
      MOSDNS: https://github.com/IrineSistiana/mosdns/releases/download/v2.1.2/mosdns-linux-amd64.zip
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - name: Update GFWList
        run: |
          set -o errexit
          set -o pipefail

          gfwlist_txt_perl_script_string='
            if (/URL Keywords/i) { $null = <> until $null =~ /^!/ }
               s#^\s*+$|^!.*+$|^@@.*+$|^\[AutoProxy.*+$|^/.*/$##i;
               s@^\|\|?|\|$@@;
               s@^https?:/?/?@@i;
               s@(?:/|%).*+$@@;
               s@\*[^.*]++$@\n@;
               s@^.*?\*[^.]*+(?=[^*]+$)@@;
               s@^\*?\.|^.*\.\*?$@@;
               s@(?=[^0-9a-zA-Z.-]).*+$@@;
               s@^\d+\.\d+\.\d+\.\d+(?::\d+)?$@@;
               s@^[^.]++$@@;
               s@^\s*+$@@
          '
          gfwlist_txt_append_domain_names() {
            printf "twimg.edgesuite.net\n"
            printf "blogspot.ae\nblogspot.al\nblogspot.am\nblogspot.ba\nblogspot.be\nblogspot.bg\nblogspot.bj\nblogspot.ca\nblogspot.cat\nblogspot.cf\nblogspot.ch\nblogspot.cl\nblogspot.co.at\nblogspot.co.id\nblogspot.co.il\nblogspot.co.ke\nblogspot.com\nblogspot.com.ar\nblogspot.com.au\nblogspot.com.br\nblogspot.com.by\nblogspot.com.co\nblogspot.com.cy\nblogspot.com.ee\nblogspot.com.eg\nblogspot.com.es\nblogspot.com.mt\nblogspot.com.ng\nblogspot.com.tr\nblogspot.com.uy\nblogspot.co.nz\nblogspot.co.uk\nblogspot.co.za\nblogspot.cv\nblogspot.cz\nblogspot.de\nblogspot.dk\nblogspot.fi\nblogspot.fr\nblogspot.gr\nblogspot.hk\nblogspot.hr\nblogspot.hu\nblogspot.ie\nblogspot.in\nblogspot.is\nblogspot.it\nblogspot.jp\nblogspot.kr\nblogspot.li\nblogspot.lt\nblogspot.lu\nblogspot.md\nblogspot.mk\nblogspot.mr\nblogspot.mx\nblogspot.my\nblogspot.nl\nblogspot.no\nblogspot.pe\nblogspot.pt\nblogspot.qa\nblogspot.re\nblogspot.ro\nblogspot.rs\nblogspot.ru\nblogspot.se\nblogspot.sg\nblogspot.si\nblogspot.sk\nblogspot.sn\nblogspot.td\nblogspot.tw\nblogspot.ug\nblogspot.vn\n"
            printf "google.ac\ngoogle.ad\ngoogle.ae\ngoogle.al\ngoogle.am\ngoogle.as\ngoogle.at\ngoogle.az\ngoogle.ba\ngoogle.be\ngoogle.bf\ngoogle.bg\ngoogle.bi\ngoogle.bj\ngoogle.bs\ngoogle.bt\ngoogle.by\ngoogle.ca\ngoogle.cat\ngoogle.cc\ngoogle.cd\ngoogle.cf\ngoogle.cg\ngoogle.ch\ngoogle.ci\ngoogle.cl\ngoogle.cm\ngoogle.cn\ngoogle.co.ao\ngoogle.co.bw\ngoogle.co.ck\ngoogle.co.cr\ngoogle.co.id\ngoogle.co.il\ngoogle.co.in\ngoogle.co.jp\ngoogle.co.ke\ngoogle.co.kr\ngoogle.co.ls\ngoogle.com\ngoogle.co.ma\ngoogle.com.af\ngoogle.com.ag\ngoogle.com.ai\ngoogle.com.ar\ngoogle.com.au\ngoogle.com.bd\ngoogle.com.bh\ngoogle.com.bn\ngoogle.com.bo\ngoogle.com.br\ngoogle.com.bz\ngoogle.com.co\ngoogle.com.cu\ngoogle.com.cy\ngoogle.com.do\ngoogle.com.ec\ngoogle.com.eg\ngoogle.com.et\ngoogle.com.fj\ngoogle.com.gh\ngoogle.com.gi\ngoogle.com.gt\ngoogle.com.hk\ngoogle.com.jm\ngoogle.com.kh\ngoogle.com.kw\ngoogle.com.lb\ngoogle.com.lc\ngoogle.com.ly\ngoogle.com.mm\ngoogle.com.mt\ngoogle.com.mx\ngoogle.com.my\ngoogle.com.na\ngoogle.com.nf\ngoogle.com.ng\ngoogle.com.ni\ngoogle.com.np\ngoogle.com.om\ngoogle.com.pa\ngoogle.com.pe\ngoogle.com.pg\ngoogle.com.ph\ngoogle.com.pk\ngoogle.com.pr\ngoogle.com.py\ngoogle.com.qa\ngoogle.com.sa\ngoogle.com.sb\ngoogle.com.sg\ngoogle.com.sl\ngoogle.com.sv\ngoogle.com.tj\ngoogle.com.tr\ngoogle.com.tw\ngoogle.com.ua\ngoogle.com.uy\ngoogle.com.vc\ngoogle.com.vn\ngoogle.co.mz\ngoogle.co.nz\ngoogle.co.th\ngoogle.co.tz\ngoogle.co.ug\ngoogle.co.uk\ngoogle.co.uz\ngoogle.co.ve\ngoogle.co.vi\ngoogle.co.za\ngoogle.co.zm\ngoogle.co.zw\ngoogle.cv\ngoogle.cz\ngoogle.de\ngoogle.dj\ngoogle.dk\ngoogle.dm\ngoogle.dz\ngoogle.ee\ngoogle.es\ngoogle.fi\ngoogle.fm\ngoogle.fr\ngoogle.ga\ngoogle.ge\ngoogle.gf\ngoogle.gg\ngoogle.gl\ngoogle.gm\ngoogle.gp\ngoogle.gr\ngoogle.gy\ngoogle.hn\ngoogle.hr\ngoogle.ht\ngoogle.hu\ngoogle.ie\ngoogle.im\ngoogle.io\ngoogle.iq\ngoogle.is\ngoogle.it\ngoogle.je\ngoogle.jo\ngoogle.kg\ngoogle.ki\ngoogle.kz\ngoogle.la\ngoogle.li\ngoogle.lk\ngoogle.lt\ngoogle.lu\ngoogle.lv\ngoogle.md\ngoogle.me\ngoogle.mg\ngoogle.mk\ngoogle.ml\ngoogle.mn\ngoogle.ms\ngoogle.mu\ngoogle.mv\ngoogle.mw\ngoogle.ne\ngoogle.net\ngoogle.nl\ngoogle.no\ngoogle.nr\ngoogle.nu\ngoogle.org\ngoogle.pl\ngoogle.pn\ngoogle.ps\ngoogle.pt\ngoogle.ro\ngoogle.rs\ngoogle.ru\ngoogle.rw\ngoogle.sc\ngoogle.se\ngoogle.sh\ngoogle.si\ngoogle.sk\ngoogle.sm\ngoogle.sn\ngoogle.so\ngoogle.sr\ngoogle.st\ngoogle.td\ngoogle.tg\ngoogle.tk\ngoogle.tl\ngoogle.tm\ngoogle.tn\ngoogle.to\ngoogle.tt\ngoogle.vg\ngoogle.vu\ngoogle.ws\n"
          }
          
          base64 -d       </dev/null &>/dev/null && base64_decode='base64 -d'
          base64 --decode </dev/null &>/dev/null && base64_decode='base64 --decode'
          [ "$base64_decode" ] || { echo "option not supported: base64 -d/--decode"; exit 1; }
          
          mkdir -p ${{ github.workspace }}/resource
          wget -q ${{ env.MOSDNS }} -O ${{ github.workspace }}/mosdns.zip
          unzip -d -q ${{ github.workspace }}/mosdns-master ${{ github.workspace }}/mosdns.zip
          
          mv ${{ github.workspace }}/mosdns-master/mosdns ${{ github.workspace }}/mosdns 
          chmod 755 ${{ github.workspace }}/mosdns
          
          wget -q ${{ env.GEOIP }} -O ${{ github.workspace }}/resource/geoip.dat
          wget -q ${{ env.GEOSITE }} -O ${{ github.workspace }}/resource/geosite.dat
          wget -q ${{ env.GFWLIST }} -O ${{ github.workspace }}/resource/gfwlist.txt
          wget -q ${{ env.CHNLIST }} -O ${{ github.workspace }}/resource/accelerated-domains.china.conf
          wget -q ${{ env.APNICIP }} -O ${{ github.workspace }}/resource/delegated-apnic-latest.txt
          wget -q ${{ env.OISD }} -O ${{ github.workspace }}/resource/oisd_dbl.txt
          
          
          ls ${{ github.workspace }}/resource
      