name: GitHub Actions Demo
on: [push]
jobs:
  Get-All-List:
    runs-on: ubuntu-latest
    env:
      GEOIP: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
      GEOSITE: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
      GFWLIST: https://raw.github.com/gfwlist/gfwlist/master/gfwlist.txt
      CHNLIST: https://raw.github.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
      APNICIP: http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest
      OISD: https://dbl.oisd.nl/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - name: Update GFWList
        run: |
          mkdir -p ${{ github.workspace }}/resource
          wget -q ${{ env.GEOIP }} -O ${{ github.workspace }}/resource/geoip.dat
          wget -q ${{ env.GEOSITE }} -O ${{ github.workspace }}/resource/geosite.dat
          wget -q ${{ env.GFWLIST }} -O ${{ github.workspace }}/resource/gfwlist.txt
          wget -q ${{ env.CHNLIST }} -O ${{ github.workspace }}/resource/accelerated-domains.china.conf
          wget -q ${{ env.APNICIP }} -O ${{ github.workspace }}/resource/delegated-apnic-latest.txt
          wget -q ${{ env.OISD }} -O ${{ github.workspace }}/resource/oisd_dbl.txt
          ls ${{ github.workspace }}
      