name: GitHub Actions Demo
on: [push]
jobs:
  Get-All-List:
    runs-on: ubuntu-latest
      env:
        GEOIP: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
        GEOSITE: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
        GEOIP_SHA256: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat.sha256sum
        GEOSITE_SHA256: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat.sha256sum
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - name: Update GFWList
        run: |
          wget -q ${{ env.GEOIP_SHA256 }}
          wget -q ${{ env.GEOSITE_SHA256 }}
          echo $(cat ${{ github.workspace }}/geoip.dat.sha256.sum)
          echo $(cat ${{ github.workspace }}/geoip.dat.sha256.sum)
          ls ${{ github.workspace }}
      